### ISSUE TITLE
ActiveRecord Statement Invalid for Group queries

### ISSUE THREAD

**Issue by kcollignon** [dwbutler/groupify#30]
On Postgresql.. running the `.in_all_groups(Group1, Group2)` or `.in_only_groups(Group1, Group2)` produces the following error:

```ruby
PG::InvalidColumnReference: ERROR:  for SELECT DISTINCT, ORDER BY expressions must appear in select list
LINE 1: ...G COUNT(group_memberships.group_id) = 2  ORDER BY users.last...
```

Appears to be something about doing a group_by in Postgres without specifying the same select fields?

**Comment by dwbutler** [comment]
This is fixed and released in version 0.6.3.

The issue was caused by joining to the `group_memberships` table and grouping by `group_memberships.member_id`. PostgreSQL couldn't figure out automatically that this is equivalent to grouping by the `id` column of the joined table. The fix explicitly joins by the `id` column. For example, if you're in the `User` model, it will now group by `users.id`.

Along the way, I set up the automated tests so that they run against SQLite, MySQL, and PostgreSQL.
