### ISSUE TITLE
Creating a named group without adding user

### ISSUE THREAD

**Issue by chriscapetown** [dwbutler/groupify#38]
Hi @dwbutler ,

How can I create a named group without adding a user to it? 

class GroupController < ApplicationController
def creategroup
	    Group.create!(params[:group])
end
def createnamedgroup
??
end
end

Thanks for your assistance.

**Comment by dwbutler** [comment]
Hi,

The idea behind a "named group" is to avoid creating an independent resource that represents a group. A named group is really just a string describing your membership, which is useful to implement things like roles.

If you want to create something independently of group memberships, you should probably be using normal groups rather than named groups.

It might help if I understood what you're trying to accomplish.

**Comment by dwbutler** [comment]
Closing, but feel free to continue the conversation.
