### ISSUE TITLE
All my tests fail after following groupify tutorial.

### ISSUE THREAD

**Issue by fergyfresh** [dwbutler/groupify#41]
ActiveRecord::StatementInvalid:         ActiveRecord::StatementInvalid: SQLite3::SQLException: table groups has no column named name: INSERT INTO "groups" ("name", "id") VALUES ('MyString', 980190962)

Is the error I am getting and it present in every test. I am not sure what I did as I am a relatively new rails dev. I tried doing my own group functionality and I think groupify migrated some of the tables I had already created? Do you have any idea of what I am talking about? It is probably my fault and I will roll back to an earlier commit before I started trying to add my own group functionality and then follow the groupify docs to re-instrument.

https://travis-ci.org/fergyfresh/carpool
https://github.com/fergyfresh/carpool/tree/groupify

**Comment by dwbutler** [comment]
Hi,

I looked at your schema.rb and your groups table indeed does not have a name column. This is because the default migration created by Groupify does not add a name column to the groups table. A name is a common requirement for groups, but Groupify does not presume that your application will actually need a name for your groups. (I have actually used Groupify to implement group membership without naming any of the groups. Groups belonged to users implicitly via membership.)

I also noticed that you did not commit the generated Groupify migration. You'll want to make sure to commit that. And don't be shy about customizing that migration to the specific needs of your application.
