### ISSUE TITLE
Question re Group Names

### ISSUE THREAD

**Issue by tilo** [dwbutler/groupify#67]
What's the reasoning behind storing the group_name in every membership record, 
rather than in the group record itself? Can groups be renamed after creation?
How is it ensured that all members use the same group_name? e.g. after renaming of the group.

**Comment by dwbutler** [comment]
Hi,

The `group_memberships.group_name` column is used for named groups. The use case here is for simple group membership needs that don't require a full Group model.

If your use case is more complicated (e.g. you want a full Group model with its own `name` column that can change), you would use groups rather than named groups. Group membership is stored in the `group_memberships.group_id` and `group_memberships.group_type` columns.
